export { OverviewTab } from './OverviewTab'
export { TariffTab } from './TariffTab'
export { PlatesTab } from './PlatesTab'
export { RoutesTab } from './RoutesTab'
export { OfficersTab } from './OfficersTab'
export { ReportsTab } from './ReportsTab'
export { SettingsTab } from './SettingsTab'
